### ISSUE TITLE
Update webpage question

### ISSUE THREAD

**Issue by venikman** [sholladay/generator-seth#2]
By default question for `url` page. We use `normalizeUrl` with out any options https://github.com/sholladay/generator-seth/blob/master/app/index.js#L163 and output `http://...` even if you have `https...`. Here we talked about it: https://github.com/sindresorhus/normalize-url/issues/62 . My issue is to add support `https` by default or make option for it

**Comment by sholladay** [comment]
Yep, sounds good. Even though many websites still don't support HTTPS, I think anyone technical enough to use this generator should be setting up new sites with HTTPS, as it is pretty easy to do these days with Let's Encrypt.

**Comment by sholladay** [comment]
Fixed in https://github.com/sholladay/generator-seth/commit/61bc62093c5bf8ac8dbd8fadef997fd9bfc0a503. :)

It now defaults to HTTPS, but if you explicitly specify HTTP, it will respect that.

I released this in version `0.8.0`.
